### PR TITLE
Fix issue with special keys that require quoting in mappings

### LINKED ISSUE #236: Incorrect handling of special keys when writing YAML files
I've run into some issues where the writer produces files that cannot be parsed again, when string keys are present, which start with special characters. A few examples are:
```julia
for char in [
    "{", "}", "[", "]", "&", "*", "#", "?", "|", "-", "<", ">",
    "=", "!", "%", "@", ":", "`", ",", "'", "\"",
]
    d = Dict(char => 0.0)
    @test YAML.load(YAML.yaml(d)) == d
end
```

As an example, `YAML.yaml(Dict(">" => 0.0))` produces:
```yaml
>: 0.0
```
which does not parse.

By comparison, Python's YAML writer successfully handles these by quoting the key:
```python
In : yaml.dump({">": 0.0})
Out: "'>': 0.0\n"
```

### PR DESCRIPTION
**Pull request by dalum**
Fixes #236

### CODE REVIEW

File: src/writer.jl [hunk 1]
```diff
@@ -73,9 +73,21 @@ end
...
         "null" # this is what the YAML parser interprets as 'nothing'
+    elseif pair[1] isa AbstractString && (
+        occursin('#', pair[1]) ||
+            any(
+                c -> startswith(pair[1], c),
+                [
+                    '{', '}', '[', ']', '&', '*', '#', '?', '|', '-', '<', '>', '=',
+                    '!', '%', '@', ':', '`', ',', '"', '\'',
+                ],
+            )
```
Comment (kescobo) [inline src/writer.jl:84]: Would this be (marginally) faster as a tuple?

Comment (kescobo) [reply src/writer.jl:84]: Or maybe as `first(pair[1]) in Set(....)`?

**Review by kescobo — COMMENTED** [review]
Thanks for the contribution! 

Is this definitely valid YAML? I don't necessarily trust python implementations to be strict about this kind of thing :laughing: @Paalon Do you know?

File: src/writer.jl (hunk 1 above)
Comment (dalum) [reply src/writer.jl:84]: You're right! Changing it to a tuple avoids an allocation and is about twice as fast. The naive `Set` version I tried has terrible performance :sweat_smile:

**Comment by dalum** [comment]
Thanks for taking a look! For context:

I deal with YAML files with keys like:
```yaml
"temperature": { ">": 0.0 }
```
They currently parse just fine. Most of the time, I only need to read them, but occasionally, they need to be read, manipulated, and written back out again. But with the current writer, they do not successfully round-trip. None of the YAML parsers I have tried are able to parse a block like:
```yaml
>: 0.0
```
because `>` has special meaning and thus needs to be quoted, when it was meant as a string key with the string value `">"`. `">"` and `">="` perfectly valid JSON keys, so I would expect a YAML writer to produce perfectly valid YAML, when presented with those string keys. More generally, I would expect that all YAML files can round-trip through the parser-writer without producing invalid YAML, which is currently not the case.

**Comment by kescobo** [comment]
I have no objection in principle, but I'm just a merge-jocky and don't have much skin in the game. But there's been talking of trying to adhere to a particular spec (#133), and I don't want to be overly permissive.

On the other hand, it seems like this is implementing a more strict version of *writing* rather than changing the permissiveness of reading, so maybe I'm jumping at shadows? I'd love for @GunnarFarneback or @Paalon to weigh in, but if they don't by the end of the week, I'll just YOLO-merge :laughing:

File: src/writer.jl [hunk 2]
```diff
@@ -73,9 +73,21 @@ end
...
         "null" # this is what the YAML parser interprets as 'nothing'
+    elseif pair[1] isa AbstractString && (
+        occursin('#', pair[1]) ||
+            any(
+                c -> startswith(pair[1], c),
+                (
+                    '{', '}', '[', ']', '&', '*', '#', '?', '|', '-', '<', '>', '=',
+                    '!', '%', '@', ':', '`', ',', '"', '\'',
+                ),
+            )
```
Comment (GunnarFarneback) [inline src/writer.jl:84]: This can be written shorter as `first(pair[1]) in "{}[]..."` or the corresponding with the tuple of characters but I haven't checked if either of them is faster than this approach. Since `#` has already been checked with `occursin`, it can be removed from this list.

File: test/runtests.jl [hunk 3]
```diff
@@ -491,4 +491,14 @@ end
     @test collect(YAML.load_all(input)) == expected
 end
 
+# issue #236 - special string keys that require enclosure in quotes
+@testset "issue #236" begin
+    for char in [
+        "{", "}", "[", "]", "&", "*", "#", "?", "|", "-", "<", ">",
+        "=", "!", "%", "@", ":", "`", ",", "'", "\"",
+    ]
+        @test YAML.load(YAML.yaml(Dict(string(char) => 0.0))) == Dict(char => 0.0)
```
Comment (GunnarFarneback) [inline test/runtests.jl:500]: Here I would opt for the shorter `char in "{}[]..."`. Then `char` actually becomes a `Char` and the `@test` line needs a small modification.

**Comment by GunnarFarneback** [comment]
Yes, this is needed and probably correct. I haven't checked if it's the exact list of characters needing quoting but it's always valid to quote and sometimes necessary, so this is definitely an improvement of the existing code.

File: src/writer.jl (hunk 2 above)
Comment (dalum) [reply src/writer.jl:84]: Thanks! Changing to `in "{}[]..."` actually has a flat runtime on my machine, which is on average better than using `any(...)`, though slightly worse, if the match is early in the tuple. Which won't be the case most of the time, so I think using `in` is the best approach

**Review by GunnarFarneback — APPROVED** [review]

**Comment by dalum** [comment]
@kescobo Do you have an idea of when a new release of YAML.jl will be tagged that includes this fix? :blush:

**Comment by kescobo** [comment]
How about now-ish? :stuck_out_tongue:
